apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  description: Build the project
  workspaces:
    - name: output
  steps:
    - name: build
      image: maven:3.8.3-openjdk-17
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.output.path)
        mvn clean install